[project]
name = "chess-understanding"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Jeffrey Kang", email = "knightdips@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.6",
    "python-chess>=1.999",
    "torch>=2.12.0",
    "tqdm>=4.67.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/chess_tools", "src/data", "src/model_training"]
